// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPDg_y0Y-9S0-FlSFEySm0XWgLcLs4lTg',
    appId: '1:434716308337:web:2c5e763324d963d38e3cd0',
    messagingSenderId: '434716308337',
    projectId: 'sansom-5bce9',
    authDomain: 'sansom-5bce9.firebaseapp.com',
    storageBucket: 'sansom-5bce9.firebasestorage.app',
    measurementId: 'G-K1KSDR9VLN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoBbmOl0Lb_0ZShFr_wPXq7-xHwAy2CJA',
    appId: '1:434716308337:android:30539f05f281d74b8e3cd0',
    messagingSenderId: '434716308337',
    projectId: 'sansom-5bce9',
    storageBucket: 'sansom-5bce9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbTxeCSkbQqIVtsV5cHRfJh1jwMG9mZg4',
    appId: '1:434716308337:ios:894ed495a01c341f8e3cd0',
    messagingSenderId: '434716308337',
    projectId: 'sansom-5bce9',
    storageBucket: 'sansom-5bce9.firebasestorage.app',
    iosBundleId: 'com.example.sansom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbTxeCSkbQqIVtsV5cHRfJh1jwMG9mZg4',
    appId: '1:434716308337:ios:894ed495a01c341f8e3cd0',
    messagingSenderId: '434716308337',
    projectId: 'sansom-5bce9',
    storageBucket: 'sansom-5bce9.firebasestorage.app',
    iosBundleId: 'com.example.sansom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPDg_y0Y-9S0-FlSFEySm0XWgLcLs4lTg',
    appId: '1:434716308337:web:4f7531d8d196c0d58e3cd0',
    messagingSenderId: '434716308337',
    projectId: 'sansom-5bce9',
    authDomain: 'sansom-5bce9.firebaseapp.com',
    storageBucket: 'sansom-5bce9.firebasestorage.app',
    measurementId: 'G-V0WM42S4RQ',
  );
}
